name: 🚀 Auto Deploy via SSH Git Pull

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Deploy to AZDigi Hosting
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 SSH vào server và git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/public_html
            git pull origin main
            echo "✅ Deploy thành công!"
